services:
  db:
    build: ../database
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secreta
      POSTGRES_DB: sistema_db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d sistema_db"]
      interval: 2s
      timeout: 5s
      retries: 5

  delete-news:
    build: . # (Ruta a la carpeta donde guardaste tu código)
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: admin
      DB_PASSWORD: secreta  # Unificamos el nombre de la variable
      DB_NAME: sistema_db
    ports:
      - "8000:8000" # Exponemos tu servicio en el puerto 8001 de Windows/WSL